#!/bin/bash
#
# PURPOSE:
#  To restructure the AMPERE project into the desired deployment 
#  and run time structure for OIG purposes.
#  
#  At the end of this script, there should be a directory structure
#  that looks like:
#
#      /opt/ampere/
#         + etc
#            + pki
#            + anubis
#	  + anubis (reference source)
#         + jars
#            + anubis-<Version>.jar
#         + logs
#
# ASSUMPTIONS:
# This script assumes that the directory /opt/ampere exists
# is owned by the appropriate user (e.g. oigdev) and that this 
# script is run as that user.
#
# We assume that the AMPERE project has been unpacked/installed
# to /opt/ampere/AMP
#
#

# ------ CONFIGURATION -----------
homedir="/opt/ampere/test"

# ------ END CONFIGURATION -----------

# ------ HELPER METHODS -----------
function verifyCwdIs() {
   verificationDirectory=$1
   varCwd="$(pwd)"
   #echo "THIS IS THE TEST:  >$varCwd< vs >$verificationDirectory<"
   if [ "$varCwd" != "$verificationDirectory" ]; then
      echo "Not in expected directory: $verificationDirectory"
      echo "ABORTING"
      exit -1
   fi 
}

function verifyDirExists() {
  if [ ! -d $1 ]; then
    echo "Missing directory>> $1"
    echo "ABORTING"
    exit -1  
  fi
}

function createDirIfNotExists() {  
  if [ ! -d $1 ]; then
    mkdir "$1"
  fi
}
# ------ END HELPER METHODS -----



# ----- VERIFIY  ------
verifyDirExists "$homedir/AMP2"

# ----- ANUBIS SETUP ------

cd $homedir
verifyCwdIs "$homedir"

createDirIfNotExists "$homedir/etc"
createDirIfNotExists "$homedir/etc/pki"
createDirIfNotExists "$homedir/etc/anubis"
createDirIfNotExists "$homedir/logs"
createDirIfNotExists "$homedir/jars"


cd $homedir/AMP/java/services/anubis/config
verifyCwdIs "$homedir/AMP/java/services/anubis/"

cp -r *


#First build basic AMPERE to make sure 
# all appropriate jars are available for the Anubis build
cd $homedir/AMP/java
verifyCwdIs "$homedir/AMP/java"
mvn install -DskipTests

# Now build the Anubis Service
cd $homedir/AMP/java/services/anubis
verifyCwdIs "$homedir/AMP/java/services/anbuis"
mvn install -DskipTests




